# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-30 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime_work',
            name='modified_time',
        ),
        migrations.RemoveField(
            model_name='time_off',
            name='modified_time',
        ),
        migrations.AddField(
            model_name='overtime_work',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='time_off',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
